export const companyList = [
    {
        cpmId: "cmp-125648",
        cmpName: "Tata Motors",
        cmpContact: 1256487966,
        cmpEmail: "sadasadasmdbasgdjgajgdjgsasdsa@gdgsajd.com",
        loc: "Kolkata",
        cmpType: "corporate",
        totalWorker: 2258,
    },
    {
        cpmId: "cmp-125648",
        cmpName: "Tata Motors",
        cmpContact: 1256487966,
        cmpEmail: "sadasadasmdbasgdjgajgdjgsasdsa@gdgsajd.com",
        loc: "Kolkata",
        cmpType: "corporate",
        totalWorker: 2258,
    },
    {
        cpmId: "cmp-125648",
        cmpName: "Tata Motors",
        cmpContact: 1256487966,
        cmpEmail: "sadasadasmdbasgdjgajgdjgsasdsa@gdgsajd.com",
        loc: "Kolkata",
        cmpType: "corporate",
        totalWorker: 2258,
    },
    {
        cpmId: "cmp-125648",
        cmpName: "Tata Motors",
        cmpContact: 1256487966,
        cmpEmail: "sadasadasmdbasgdjgajgdjgsasdsa@gdgsajd.com",
        loc: "Kolkata",
        cmpType: "corporate",
        totalWorker: 2258,
    },
    {
        cpmId: "cmp-125648",
        cmpName: "Tata Motors",
        cmpContact: 1256487966,
        cmpEmail: "sadasadasmdbasgdjgajgdjgsasdsa@gdgsajd.com",
        loc: "Kolkata",
        cmpType: "corporate",
        totalWorker: 2258,
    },
    {
        cpmId: "cmp-125648",
        cmpName: "Tata Motors",
        cmpContact: 1256487966,
        cmpEmail: "sadasadasmdbasgdjgajgdjgsasdsa@gdgsajd.com",
        loc: "Kolkata",
        cmpType: "corporate",
        totalWorker: 2258,
    },
    {
        cpmId: "cmp-125648",
        cmpName: "Tata Motors",
        cmpContact: 1256487966,
        cmpEmail: "sadasadasmdbasgdjgajgdjgsasdsa@gdgsajd.com",
        loc: "Kolkata",
        cmpType: "corporate",
        totalWorker: 2258,
    },
    {
        cpmId: "cmp-125648",
        cmpName: "Tata Motors",
        cmpContact: 1256487966,
        cmpEmail: "sadasadasmdbasgdjgajgdjgsasdsa@gdgsajd.com",
        loc: "Kolkata",
        cmpType: "corporate",
        totalWorker: 2258,
    },
    {
        cpmId: "cmp-125648",
        cmpName: "Tata Motors",
        cmpContact: 1256487966,
        cmpEmail: "sadasadasmdbasgdjgajgdjgsasdsa@gdgsajd.com",
        loc: "Kolkata",
        cmpType: "corporate",
        totalWorker: 2258,
    },
];
